blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://developers.applovin.com/en/max/cordova/overview/integration
    about: Documentation for the AppLovin MAX Cordova Plugin
  - name: Support
    url: https://developers.applovin.com/en/max/faq/common-questions-from-publishers
    about: Answers to common questions and support for AppLovin MAX
